# Generated by Django 4.2.5 on 2025-03-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0002_alter_comment_unique_together_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_date',
        ),
    ]
