# Generated by Django 5.1.7 on 2025-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0002_alter_comment_unique_together_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
