# Generated by Django 4.2.5 on 2025-04-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0008_rename_purchase_priority_purchasepriority_and_more'),
        ('goodBuy_web', '0002_payment_profile_payment_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_Account',
            new_name='PaymentAccount',
        ),
    ]
