# Generated by Django 4.2.5 on 2025-04-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0003_rename_payment_account_paymentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='goodBuy_web.payment'),
        ),
    ]
