# Generated by Django 4.2.5 on 2025-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0004_remove_paymentaccount_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(fields=('user', 'black_user'), name='unique_blacklist_pair'),
        ),
    ]
