# Generated by Django 4.2.5 on 2025-04-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0006_paymentaccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentaccount',
            name='unique_user_payment_account',
        ),
    ]
