# Generated by Django 4.2.5 on 2025-04-22 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import goodBuy_web.models.user_address


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0007_remove_paymentaccount_unique_user_payment_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, validators=[goodBuy_web.models.user_address.validate_tw_mobile], verbose_name='手機號碼')),
                ('city', models.CharField(choices=[('Keelung City', '基隆市'), ('New Taipei City', '新北市'), ('Taipei City', '台北市'), ('Taoyuan City', '桃園市'), ('Hsinchu County', '新竹縣'), ('Hsinchu City', '新竹市'), ('Miaoli County', '苗栗縣'), ('Taichung City', '台中市'), ('Changhua County', '彰化縣'), ('Nantou County', '南投縣'), ('Yunlin County', '雲林縣'), ('Chiayi County', '嘉義縣'), ('Chiayi City', '嘉義市'), ('Tainan City', '台南市'), ('Kaohsiung City', '高雄市'), ('Pingtung County', '屏東縣'), ('Yilan County', '宜蘭縣'), ('Hualien County', '花蓮縣'), ('Taitung County', '台東縣'), ('Penghu County', '澎湖縣'), ('Kinmen County', '金門縣'), ('Lienchiang County', '連江縣')], default='', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
