# Generated by Django 4.2.5 on 2025-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0008_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(fields=('user', 'payment', 'account'), name='unique_payment_account'),
        ),
    ]
