# Generated by Django 4.2.5 on 2025-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0009_paymentaccount_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(fields=('user', 'phone', 'city', 'address'), name='unique_address_account'),
        ),
    ]
