# Generated by Django 4.2.5 on 2025-04-06 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_shop', '0008_rename_purchase_priority_purchasepriority_and_more'),
        ('goodBuy_want', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Want_Back',
            new_name='WantBack',
        ),
        migrations.RenameModel(
            old_name='Want_Footprints',
            new_name='WantFootprints',
        ),
    ]
