# Generated by Django 4.2.5 on 2025-03-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_want', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Want_Footprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_want.want')),
            ],
        ),
    ]
