# Generated by Django 4.2.5 on 2025-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_want', '0002_rename_want_back_wantback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantback',
            name='text',
        ),
        migrations.AddField(
            model_name='want',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
