# Generated by Django 4.2.5 on 2025-04-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_want', '0003_remove_wantback_text_want_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='want',
            name='img',
        ),
    ]
