# Generated by Django 4.2.5 on 2025-04-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_tag', '0002_rename_tag_collect_tagcollect'),
        ('goodBuy_want', '0004_remove_want_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_tag.tag')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_want.want')),
            ],
        ),
        migrations.CreateModel(
            name='wantImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='want_img/')),
                ('is_cover', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goodBuy_want.want')),
            ],
        ),
    ]
