# Generated by Django 4.2.5 on 2025-04-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_tag', '0003_tagcollect_unique_user_tag_collect'),
        ('goodBuy_want', '0006_want_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodBuy_tag.tag'),
            preserve_default=False,
        ),
    ]
