# Generated by Django 4.2.5 on 2025-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_want', '0008_alter_wantback_shop_wanttag_unique_want_tag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wantback',
            constraint=models.UniqueConstraint(fields=('user', 'want', 'shop'), name='unique_want_reply'),
        ),
    ]
