# Generated by Django 4.2.5 on 2025-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_want', '0009_wantback_unique_want_reply'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wantfootprints',
            constraint=models.UniqueConstraint(fields=('user', 'want'), name='unique_user_want_footprints'),
        ),
    ]
