# Generated by Django 4.2.5 on 2025-04-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_want', '0010_wantfootprints_unique_user_want_footprints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='want',
            old_name='update_time',
            new_name='update',
        ),
    ]
