# Generated by Django 4.2.5 on 2025-06-09 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_want', '0011_rename_update_time_want_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantfootprints',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='wantfootprints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wantfootprints',
            constraint=models.UniqueConstraint(fields=('session_key', 'want'), name='unique_session_want_footprints'),
        ),
    ]
