# Generated by Django 4.2.5 on 2025-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_want', '0012_wantfootprints_session_key_alter_wantfootprints_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantfootprints',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
