# Generated by Django 4.2.5 on 2025-06-21 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_want', '0013_alter_wantfootprints_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(max_length=50)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clicked', models.BooleanField(default=False)),
                ('algorithm_version', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_want.want')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'want'], name='goodBuy_wan_user_id_951b98_idx'), models.Index(fields=['session_key', 'want'], name='goodBuy_wan_session_0db877_idx'), models.Index(fields=['recommended_at'], name='goodBuy_wan_recomme_febfd5_idx')],
            },
        ),
    ]
