# Generated by Django 4.2.5 on 2025-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_tag', '0002_rename_tag_collect_tagcollect'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tagcollect',
            constraint=models.UniqueConstraint(fields=('user', 'tag'), name='unique_user_tag_collect'),
        ),
    ]
