# Generated by Django 4.2.5 on 2025-04-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0008_rename_purchase_priority_purchasepriority_and_more'),
        ('goodBuy_order', '0002_cart_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pay_State',
            new_name='OrderState',
        ),
        migrations.RenameModel(
            old_name='Order_State',
            new_name='PayState',
        ),
        migrations.RenameModel(
            old_name='Product_Order',
            new_name='ProductOrder',
        ),
    ]
