# Generated by Django 4.2.5 on 2025-04-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0003_rename_pay_state_orderstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_order.orderstate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_order.paystate'),
        ),
    ]
