# Generated by Django 4.2.5 on 2025-04-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0008_rename_purchase_priority_purchasepriority_and_more'),
        ('goodBuy_order', '0004_alter_order_order_state_alter_order_pay_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_shop.product'),
        ),
    ]
