# Generated by Django 4.2.5 on 2025-04-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0005_productorder_product_img_productorder_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
