# Generated by Django 4.2.5 on 2025-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0006_alter_productorder_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='second_supplement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(),
        ),
    ]
