# Generated by Django 4.2.5 on 2025-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0007_alter_order_pay_alter_order_second_supplement_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
    ]
