# Generated by Django 4.2.5 on 2025-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0008_productorder_unique_order_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='unique_user_order_comment'),
        ),
    ]
