# Generated by Django 4.2.5 on 2025-04-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0010_cart_unique_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_account_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
