# Generated by Django 4.2.5 on 2025-04-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0013_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_account_info',
        ),
    ]
