# Generated by Django 4.2.5 on 2025-04-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0007_remove_paymentaccount_unique_user_payment_account'),
        ('goodBuy_order', '0015_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_web.paymentaccount'),
        ),
    ]
