# Generated by Django 4.2.5 on 2025-04-20 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_shop', '0018_alter_shopfootprints_unique_together_and_more'),
        ('goodBuy_order', '0016_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_proof',
        ),
        migrations.CreateModel(
            name='PurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('pay_time', models.DateTimeField(auto_now_add=True)),
                ('pay_proof', models.ImageField(blank=True, null=True, upload_to='pay_proofs/')),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='goodBuy_order.order')),
            ],
        ),
        migrations.CreateModel(
            name='IntentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_products', to='goodBuy_order.purchaseintent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.product')),
            ],
            options={
                'unique_together': {('intent', 'product')},
            },
        ),
    ]
