# Generated by Django 4.2.5 on 2025-04-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0017_remove_order_pay_proof_purchaseintent_orderpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
