# Generated by Django 4.2.5 on 2025-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0018_remove_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('full', '一次付款'), ('split', '定金＋尾款')], default='full', max_length=10),
        ),
    ]
