# Generated by Django 4.2.5 on 2025-04-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_web', '0008_useraddress'),
        ('goodBuy_shop', '0020_shop_deposit_ratio'),
        ('goodBuy_order', '0019_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_web.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_shop.shoppayment'),
        ),
    ]
