# Generated by Django 4.2.5 on 2025-04-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0020_order_address_order_payment_method_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method_text',
            new_name='display_payment_method',
        ),
    ]
