# Generated by Django 4.2.5 on 2025-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0021_rename_payment_method_text_order_display_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='display_payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_name',
        ),
    ]
