# Generated by Django 4.2.5 on 2025-04-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0021_product_is_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_order', '0022_remove_order_display_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shoppayment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
