# Generated by Django 4.2.5 on 2025-04-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0022_alter_product_shop_alter_shop_owner'),
        ('goodBuy_order', '0023_alter_order_payment_method_alter_order_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.product'),
            preserve_default=False,
        ),
    ]
