# Generated by Django 4.2.5 on 2025-04-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0022_alter_product_shop_alter_shop_owner'),
        ('goodBuy_order', '0024_remove_productorder_product_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='is_confirmed_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='is_paid_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='is_rejected_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='shop_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_shop.shoppayment'),
        ),
    ]
