# Generated by Django 4.2.5 on 2025-04-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0025_remove_order_payment_method_orderpayment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_category',
            field=models.CharField(choices=[('cash_on_delivery', '取貨付款'), ('remittance', '匯款')], default='cash_on_delivery', max_length=20),
        ),
    ]
