# Generated by Django 4.2.5 on 2025-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0026_order_payment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='is_confirmed_by_seller',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='is_rejected_by_seller',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='seller_state',
            field=models.CharField(choices=[('wait confirmed', '待確認'), ('confirmed', '已收到'), ('returned', '已退回')], default='wait confirmed', max_length=20),
        ),
    ]
