# Generated by Django 4.2.5 on 2025-04-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0027_remove_orderpayment_is_confirmed_by_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='quantity',
        ),
    ]
