# Generated by Django 4.2.5 on 2025-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0028_rename_amount_productorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='seller_state',
            field=models.CharField(choices=[('wait confirmed', '待確認'), ('confirmed', '已收到'), ('returned', '已退回'), ('none', '取貨付款')], default='wait confirmed', max_length=20),
        ),
    ]
