# Generated by Django 4.2.5 on 2025-04-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0029_alter_orderpayment_seller_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='amount',
            new_name='quantity',
        ),
    ]
