# Generated by Django 4.2.5 on 2025-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0030_rename_amount_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='seller_state',
            field=models.CharField(choices=[('wait_confirmed', '待確認'), ('confirmed', '已收到'), ('returned', '已退回'), ('overdue', '已逾期'), ('none', '取貨付款')], default='wait_confirmed', max_length=20),
        ),
    ]
