# Generated by Django 4.2.5 on 2025-03-27 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.permission')),
                ('purchase_priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.purchase_priority')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.payment')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop_state'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('introduce', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop')),
            ],
        ),
    ]
