# Generated by Django 4.2.5 on 2025-04-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_tag', '0001_initial'),
        ('goodBuy_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_collect',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag_collect',
            name='user',
        ),
        migrations.AlterField(
            model_name='shop_tag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodBuy_tag.tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tag_Collect',
        ),
    ]
