# Generated by Django 4.2.5 on 2025-04-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0002_remove_tag_collect_tag_remove_tag_collect_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_payment',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop_payment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='payment_img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shop_img/'),
        ),
    ]
