# Generated by Django 4.2.5 on 2025-04-03 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0003_shop_payment_account_shop_payment_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
