# Generated by Django 4.2.5 on 2025-04-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0005_remove_shop_payment_account_remove_shop_payment_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_payment',
            old_name='payment',
            new_name='payment_account',
        ),
    ]
