# Generated by Django 4.2.5 on 2025-04-06 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_web', '0002_payment_profile_payment_account'),
        ('goodBuy_tag', '0001_initial'),
        ('goodBuy_shop', '0007_shop_announcement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_Priority',
            new_name='PurchasePriority',
        ),
        migrations.RenameModel(
            old_name='Shop_Collect',
            new_name='ShopCollect',
        ),
        migrations.RenameModel(
            old_name='Shop_Footprints',
            new_name='ShopFootprints',
        ),
        migrations.RenameModel(
            old_name='Shop_Payment',
            new_name='ShopPayment',
        ),
        migrations.RenameModel(
            old_name='Shop_State',
            new_name='ShopState',
        ),
        migrations.RenameModel(
            old_name='Shop_Tag',
            new_name='ShopTag',
        ),
    ]
