# Generated by Django 4.2.5 on 2025-04-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0008_rename_purchase_priority_purchasepriority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop'),
        ),
    ]
