# Generated by Django 4.2.5 on 2025-04-07 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_shop', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopfootprints',
            unique_together={('user', 'shop')},
        ),
    ]
