# Generated by Django 4.2.5 on 2025-04-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0011_alter_shopfootprints_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop')),
            ],
        ),
        migrations.DeleteModel(
            name='Shop_Announcement',
        ),
    ]
