# Generated by Django 4.2.5 on 2025-04-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0012_shopannouncement_delete_shop_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='img',
        ),
    ]
