# Generated by Django 4.2.5 on 2025-04-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0013_remove_shop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ShopImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='shop_img/')),
                ('is_cover', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goodBuy_shop.shop')),
            ],
        ),
    ]
