# Generated by Django 4.2.5 on 2025-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0014_alter_shop_end_time_alter_shop_start_time_shopimg'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppayment',
            constraint=models.UniqueConstraint(fields=('shop', 'payment_account'), name='unique_shop_payment_account'),
        ),
    ]
