# Generated by Django 4.2.5 on 2025-04-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_tag', '0003_tagcollect_unique_user_tag_collect'),
        ('goodBuy_shop', '0015_shoppayment_unique_shop_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodBuy_tag.tag'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shoptag',
            constraint=models.UniqueConstraint(fields=('shop', 'tag'), name='unique_shop_tag'),
        ),
    ]
