# Generated by Django 4.2.5 on 2025-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0016_alter_shoptag_tag_shoptag_unique_shop_tag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopcollect',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_collect'),
        ),
    ]
