# Generated by Django 4.2.5 on 2025-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0017_shopcollect_unique_user_shop_collect'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopfootprints',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='shopfootprints',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_footprints'),
        ),
    ]
