# Generated by Django 4.2.5 on 2025-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0019_shop_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deposit_ratio',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
