# Generated by Django 4.2.5 on 2025-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0022_alter_product_shop_alter_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_rush_settled',
            field=models.BooleanField(default=False),
        ),
    ]
