# Generated by Django 4.2.5 on 2025-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0023_shop_is_rush_settled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='date',
            new_name='update',
        ),
        migrations.AddField(
            model_name='shop',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
    ]
