# Generated by Django 4.2.5 on 2025-04-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0024_rename_date_shop_update_shop_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopannouncement',
            old_name='date',
            new_name='update',
        ),
    ]
