# Generated by Django 4.2.5 on 2025-06-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_shop', '0026_shopfootprints_session_key_alter_shopfootprints_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(max_length=50)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clicked', models.BooleanField(default=False)),
                ('algorithm_version', models.CharField(blank=True, max_length=50, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodBuy_shop.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'shop'], name='goodBuy_sho_user_id_a01024_idx'), models.Index(fields=['session_key', 'shop'], name='goodBuy_sho_session_ac820b_idx'), models.Index(fields=['recommended_at'], name='goodBuy_sho_recomme_5338bd_idx')],
            },
        ),
    ]
